<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <UseWPF>true</UseWPF>
    <AssemblyName>DeckContext</AssemblyName>
    <RootNamespace>DeckContext.App</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeckContext.Application\DeckContext.Application.csproj" />
  </ItemGroup>
</Project>
