<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\DeckContext.Export\DeckContext.Export.csproj" />
    <ProjectReference Include="..\..\src\DeckContext.OpenXml\DeckContext.OpenXml.csproj" />
  </ItemGroup>
</Project>
