<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DocumentFormat.OpenXml" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DeckContext.Application\DeckContext.Application.csproj" />
    <ProjectReference Include="..\DeckContext.Domain\DeckContext.Domain.csproj" />
  </ItemGroup>
</Project>
